services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    volumes:
      - db_data:/var/lib/mysql
    networks: [app-network]   # <- ADD
    
  service-image:
    build: ./microservice
    ports:
      - "3001:3000"
    restart: always
    environment:
      DB_HOST: image-db
      DB_USER: imageuser
      DB_PASS: imagepass
      DB_NAME: imagedb
      DB_PORT: 3306
    depends_on:
      - image-db
    networks: [app-network]
    volumes:
      - ./microservice/uploads:/usr/src/app/uploads   # <â€” persiste uploads

  image-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imagedb
      MYSQL_USER: imageuser
      MYSQL_PASSWORD: imagepass
    ports:
      - "3307:3306"
    volumes:
      - users_data:/var/lib/mysql
    networks: [app-network]   # <- ADD
    
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks: [app-network]

  backend:
    build: ./Backend
    container_name: backend
    env_file:
      - ./Backend/.env
    depends_on:
      - database
      - service-image
      - redis            # <- add
    environment:
      IMAGE_SERVICE_URL: http://service-image:3000   # <- ADD
    ports:
      - "3000:3000"
    networks: [app-network]   # <- ADD
    
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - service-image
    networks: [app-network]

volumes:
  db_data:
    driver: local
  users_data:
    driver: local

networks:
  app-network:
    driver: bridge
